Components: Remove browserlist setting
from package.json. Otherwise the Discovery plugin fails with:

```
BrowserslistError: Unknown browser query `dead`
```

Because kolibri-tools has old dependencies for CSS loading.

https://phabricator.endlessm.com/T31989