discovery search: Paginate fetching nodes
When there's a lot of nodes in the search result we need to paginate to
avoid the backend error:

django.db.utils.OperationalError: Expression tree is too large (maximum depth 1000)

https://phabricator.endlessm.com/T32306